### ISSUE TITLE
Feature - Tags

### ISSUE THREAD

**Issue by rmj1405** [AY2223S2-CS2103T-T11-1/tp#103]

**Comment by Jnjy** [comment]
Functionalities of tags:
- [ ] Add predefined tag
- [ ] List predefined tags
- [ ] Delete tag (Justin)
- [ ] Tag a food item
- [ ] Untag a food item
- [ ] Edit tag (Justin)
- [ ] List by tag (Justin)
- [ ] Delete by tag (Justin)

**Comment by Jnjy** [comment]
edit tag - removed from implementing

testing brings forward to v1.3b
