### ISSUE TITLE
UI Main Window bugs and todos

### ISSUE THREAD

**Issue by rmj1405** [AY2223S2-CS2103T-T11-1/tp#137]
TODOS:
- [x] link enter button with event handler to input an item
- [x] design enter button to match mockup
- [x] make scrollbar match colour scheme

BUGS:
- [x] food panel is not rounded, scroll pane colour overflow

![Image](https://user-images.githubusercontent.com/35266074/227208725-e192f23e-2920-48bf-8dc0-eb8e03dc6690.png)

- [x] Adding too many tags made it overflow

![image](https://user-images.githubusercontent.com/79987741/227832211-c05e65da-685c-4cf4-84f4-b11e79dce477.png)

- [x] help window renders behind main window
- [x] button is not fully coloured

![Image](https://user-images.githubusercontent.com/35266074/227209199-f1c7ad2c-6252-470b-8b72-fe282ecbd8d6.png)

- [x] button should be same height as input box

![image](https://user-images.githubusercontent.com/79987741/227832900-f287dbad-40bf-4dd5-b9a1-60daeec623e7.png)

**Comment by Jnjy** [comment]
Hi, just want to check if there is any changes to the text colour when the command entered is an invalid command or any sorts of error response?

**Comment by nigelteosw** [comment]
enter button might need abit more time, might need to parse the entered text up to MainWindow.java. Unless there is a better way to do it?
