### ISSUE TITLE
[PE-D][Tester A] Cannot add item when the quantity is too large

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T11-1/tp#217]
![image.png](https://raw.githubusercontent.com/Douglch/ped/main/files/763915a8-54e5-4a11-92af-e94232db5be8.png)

Maybe you can set a reasonable limit to the quantity or mention it briefly in the UG.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Douglch/ped#5

**Comment by Jnjy** [comment]
Will take in the suggestion of the reviewee and set an upper limit to quantity in the app and mention it explicitly in UG.
