### ISSUE TITLE
[PE-D][Tester C] Formatting mistake in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T11-1/tp#218]
/br can be seen by the reader.

![Trying out your first command!.png](https://raw.githubusercontent.com/StefanosAv/ped/main/files/62b14897-5ce7-4652-b5fe-914fc85b014c.png)
￼

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: StefanosAv/ped#3

**Comment by Bisceto** [comment]
Resolved
