### ISSUE TITLE
[PE-D][Tester D] Error message shown despite command being executed for 'createtag'

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T11-1/tp#252]
Context: The tag 'Nice' is already an existing tag, 'liquid'  and 'solid' are not existing tags

Action: Tried to create the nice, liquid and solid tags

Outcome: error message is shown, 'liquid' is being added to the tag list, but the 'solid' is not added into the tag list as shown in the screenshots below (not sure why the liquid is being added and solid is not?) 

![image.png](https://raw.githubusercontent.com/weilin1202/ped/main/files/44b127e2-890b-4b8f-9065-3aae5c742715.png)

![image.png](https://raw.githubusercontent.com/weilin1202/ped/main/files/20e554f6-b5bd-456f-af5a-f395aaf81d11.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: weilin1202/ped#13

**Comment by Jnjy** [comment]
Can use CS2102 "all or none" principle to not allow insertion of new tags if any one of the tags is invalid.
