### ISSUE TITLE
[PE-D][Tester B] Finding food item by tags

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T11-1/tp#261]
As per the documentation, it would seem that all food items that have all of the tags specified will be shown and listed by `listbytag`.

![image.png](https://raw.githubusercontent.com/LiuMC-SG/ped/main/files/44b28bad-a838-44ff-b0e1-9eee70e31d71.png)

However, the listing is by an `or` principle instead of an `and` principle as shown below.

![image.png](https://raw.githubusercontent.com/LiuMC-SG/ped/main/files/efcd1148-ec3f-453d-b857-7bac8cbed068.png)

Hence, there needs to be a fix in the functionality of `listbytag` to work in a `and` context instead of an `or` context.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: LiuMC-SG/ped#23

**Comment by Bisceto** [comment]
We have edited the UG to mention that it will follow the 'or' principle.

"Shows a list of all food item in WIFE by specified tag(s). Food items that contains any tags specified in the command will be listed."
